version: '3.9'

networks:
  fullstack-network:

services:

  production_database:
      image: mariadb:10.7.3
      container_name: ProductionDatabase
      restart: on-failure
      environment:
        MARIADB_USER: ${MARIADB_USER}
        MARIADB_PASSWORD: ${MARIADB_PASSWORD}
        MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
        MARIADB_DATABASE: ${MARIADB_DATABASE}
      volumes:
        - ./Images/database:/var/lib/mysql
      ports:
        - '3308:3306'
      networks:
          - fullstack-network

  production_laravel:
    container_name: ProductionLaravel
    build:
      context: .
      dockerfile: Dockerfile.Webserver
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - '8080:80'
    volumes:
      - ./Website:/var/www/laravel_docker
      - ./Images/website/apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./Images/website/php:/usr/local/etc/php
    depends_on:
      - production_database
    networks:
      - fullstack-network


  old_site:
    container_name: OldSite
    build:
      context: .
      dockerfile: Dockerfile.OldSite
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - '3305:80'
    volumes:
      - ./Old_env:/var/www/old
      - ./Images/website/old_site/default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./Images/website/php:/usr/local/etc/php
    depends_on:
      - production_database
    networks:
      - fullstack-network
