FROM php:8.0-apache

ARG UID
ARG GID

ENV UID=${UID}
ENV GID=${GID}

RUN apt-get update -y
RUN ["apt-get", "install", "-y", "openssl", "nano", "libcurl4-openssl-dev", "libzip-dev", "libxml2-dev"]
RUN docker-php-ext-install curl zip xml pdo_mysql dom fileinfo tokenizer mysqli

RUN mkdir -p /var/www/old/
WORKDIR /var/www/old/

RUN chown -R www-data:www-data /var/www/old/
RUN chmod -R 775 /var/www/old/

