INSERT INTO `category` (`id`, `name`) VALUES
(1, 'SOEP'),
(2, 'VOORGERECHT'),
(3, 'BAMI EN NASI GERECHTEN'),
(4, 'COMBINATIE GERECHTEN (met witte rijst)'),
(5, 'MIHOEN GERECHTEN'),
(6, 'CHINESE BAMI GERECHTEN'),
(7, 'INDISCHE GERECHTEN'),
(8, 'EIERGERECHTEN (met witte rijst)'),
(9, 'GROENTEN GERECHTEN (met witte rijst)'),
(10, 'VLEES GERECHTEN (met witte rijst)'),
(11, 'KIP GERECHTEN (met witte rijst)'),
(12, 'GARNALEN GERECHTEN (met witte rijst)'),
(13, 'OSSENHAAS GERECHTEN (met witte rijst)'),
(14, 'VISSEN GERECHTEN (met witte rijst)'),
(15, 'PEKING EEND GERECHTEN (met witte rijst)'),
(16, 'TIEPAN SPECIALITEITEN (met witte rijst)'),
(17, 'VEGETARISCHE GERECHTEN (met witte rijst)'),
(18, 'KINDERMENUS'),
(19, 'RIJSTTAFELS'),
(20, 'BUFFET'),
(21, 'DIVERSEN');
