# This is a basic workflow to help you get started with Actions

name: DevelopActions

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the Production branch
  push:
    branches: [ Develop ]
  pull_request:
    branches: [ Develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  update-test:
    name: Merge develop into test branch
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: merge
        uses: mtanzi/action-automerge@v1
        id: merge
        with:
          github_token: ${{ github.token }}
          source: 'Develop'
          target: 'Test'

  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      

